name: CI-Workflow
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  the_job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout-Source-Code-Step
        uses: actions/checkout@v2



      - name: Set-up-JDK-Step
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache-local-Maven-repository-Step
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Configure-Git-User-Step
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: The-Step
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
          REPSY_PASS: ${{ secrets.REPSY_PASS }}
        run: |
          mvn clean deploy --batch-mode --settings .github/mvn-settings.xml
