name: CI-Workflow
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout-Source-Code-Step
        uses: actions/checkout@v2



      - name: Set-up-JDK-Step
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache-local-Maven-repository-Step
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-






      - name: Build-Step
        run: |
          # mvn clean deploy
          # this magical incantation fails the script if mvn fails; otherwise, the script will not fail unless grep fails.
          set -o pipefail
          mvn --batch-mode clean deploy --settings .github/mvn-settings.xml 
          # | grep -v 'Download.* http'
        # --file pom.xml
