name: Release-Workflow
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to checkout when making the release."
        required: true
        default: "master"

jobs:
  the_job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout-Source-Code-Step
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set-up-JDK-Step
        uses: actions/setup-java@v1
        with:
          java-version: 17
          # distribution: 'zulu'

      - name: Cache-local-Maven-repository-Step
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Configure-Git-User-Step
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: The-Step
        run: |



          mvn release:prepare release:perform --batch-mode --settings .github/mvn-settings.xml
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
